---
# This is an example configuration file for the AdWords API client library.
# Please fill in the required fields, and copy it over to your home directory.
:authentication:
  # Authentication method, for web applications OAuth is recommended.
  :method: OAuth2

  # Auth parameters for OAuth2.0 method.
  # Set the OAuth2 client id and secret. Register your application here to
  # obtain these values:
  #   https://code.google.com/apis/console#access
  :oauth2_client_id: INSERT_OAUTH2_CLIENT_ID_HERE
  :oauth2_client_secret: INSERT_OAUTH2_CLIENT_SECRET_HERE
  # Optional, see: https://developers.google.com/accounts/docs/OAuth2WebServer
  #:oauth2_state: INSERT_OAUTH2_STATE_HERE
  #:oauth2_access_type: INSERT_OAUTH2_ACCESS_TYPE_HERE
  #:oauth2_approval_prompt: INSERT_OAUTH2_APPROVAL_PROMPT_HERE
  # Callback is set up by the application at runtime.
  #:oauth2_callback: INSERT_OAUTH2_CALLBACK_URL_HERE

  # Other parameters.
  :developer_token: INSERT_YOUR_DEVELOPER_TOKEN_HERE
  # If you access only one account you can specify it here.
  # :client_customer_id: INSERT_YOUR_CLIENT_CUSTOMER_ID_HERE
  :user_agent: demo-rails
:service:
  # Only production environment is available now, see: http://goo.gl/Plu3o
  :environment: PRODUCTION
:connection:
  # Enable to request all responses to be compressed.
  :enable_gzip: false
  # If your proxy connection requires authentication, make sure to include it in
  # the URL, e.g.: http://user:password@proxy_hostname:8080
  # :proxy: INSERT_PROXY_HERE
:library:
  :log_level: INFO
